### ISSUE TITLE
Storing templates in MongoDB

### ISSUE THREAD

**Issue by sanjay-94** [m3nu/invoice2data#101]
As being discussed in the ideas page, building web services will help users manage templates better. This is a stepping stone towards that idea. If we can store templates in a database, we will be able to write web services to manage them easily. Today I had some free time and I began experimenting on this idea. It turned out to be pretty fruitful. 

For the databases part, I chose MongoDB due to its flexible schemas which are a necessity for our highly dynamic templates. Also MongoDB is highly scalable and has a good open source community. 

I installed MongoDB 3.6.3 on my mac and created a database called invoice2data, a collection called template and created a document for com.oyo.invoice.yml. The following command was used to create the document. 

```
db.template.insert({ issuer: 'OYO', fields: { amount: "GrandTotalRs(\u005cd+)", date: 'Date:(\u005cd{1,2}\/\u005cd{1,2}\/\u005cd{1,4})', invoice_number: '([A-Z0-9]+)CashatHotel' }, keywords: ['OYO', 'Oravel', 'Stays'], options: { currency: 'INR', decimal_seperator: '.', remove_whitespace: 'true' }})
```

I then created a function called read_templates_from_db() which does the same thing as read_templates instead it reads from the database. The function definition is given below. 

```
def read_templates_from_db():
    logger.info("Loading templates from DB")
    output = []
    client = MongoClient()
    db = client.invoice2data
    cursor = db.template.find()
    for doc in cursor:
        del doc['_id']
        doc['template_name'] = doc['issuer']
        
        # Test if all required fields are in template:
        assert 'keywords' in doc.keys(), 'Missing keywords field.'
        required_fields = ['date', 'amount', 'invoice_number']
        assert len(set(required_fields).intersection(doc['fields'].keys())) == len(required_fields), \
            'Missing required key in template. Found {}'.format(doc['fields'].keys())
        
        # Keywords as list, if only one.
        if type(doc['keywords']) is not list:
            doc['keywords'] = [doc['keywords']]
        output.append(InvoiceTemplate(doc))

   return output
```

And then I replaced all the calls to read_templates() from main.py with read_templates_from_db() and it works perfectly. The template is read from the database and fields are extracted correctly. Here is the output. 

```
INFO:root:Loading templates from DB
INFO:root:Loading templates from DB
DEBUG:__main__:START pdftotext result ===========================
DEBUG:__main__:                     PAYMENT RECEIPT
...
...
...
122001|Phone:08010044466|Email:
contactus@oyorooms.com
DEBUG:root:END optimized_str ==========================
DEBUG:root:Date parsing: languages=[] date_formats=[]
DEBUG:root:Float parsing: decimal separator=.
DEBUG:root:keywords=['OYO', 'Oravel', 'Stays']
DEBUG:root:{'remove_whitespace': 'true', 'remove_accents': False, 'lowercase': False, 'currency': 'INR', 'date_formats': [], 'languages': [], 'decimal_separator': '.', 'replace': [], 'decimal_seperator': '.'}
DEBUG:root:field=amount | regexp=GrandTotalRs(\d+)
DEBUG:root:res_find=['1939']
DEBUG:root:field=date | regexp=Date:(\d{1,2}/\d{1,2}/\d{1,4})
DEBUG:root:res_find=['31/12/2017']
DEBUG:root:result of date parsing=2017-12-31 00:00:00
DEBUG:root:field=invoice_number | regexp=([A-Z0-9]+)CashatHotel
DEBUG:root:res_find=['IBZY2087']
DEBUG:root:{'issuer': 'OYO', 'amount': 1939.0, 'date': datetime.datetime(2017, 12, 31, 0, 0), 'invoice_number': 'IBZY2087', 'currency': 'INR', 'desc': 'Invoice IBZY2087 from OYO'}
INFO:__main__:{'issuer': 'OYO', 'amount': 1939.0, 'date': datetime.datetime(2017, 12, 31, 0, 0), 'invoice_number': 'IBZY2087', 'currency': 'INR', 'desc': 'Invoice IBZY2087 from OYO'}

Process finished with exit code 0
```

I would like to know your feedback about this approach. I believe if we are to store all the templates in databases, we can write REST API's to fetch them or to update them, hence making template management more easy. Then we can build GUI's for users without knowledge of regex to manage templates easily. 
I did not checkin the code yet, as I wanted to get feedback from you about what you think about this approach. 

Cheers!

**Comment by m3nu** [comment]
That's a big plan. I'm just afraid it's not related to the core functionality and running and maintaining this kind of web service in the long run won't be easy. The API model you suggest is also too slow.

Maybe better to start a bit smaller and focus on core functionality first. Like having working test to validate templates.

**Comment by sanjay-94** [comment]
Got it @manuel. Closing this issue as it’s not related to core functionality.
