### ISSUE TITLE
Warn on version-mismatch with xpdf

### ISSUE THREAD

**Issue by alexis-via** [m3nu/invoice2data#11]
It's great to be able to use the latest improvements of xpdf (option -table), but I find it a bit hard to oblige all users to use the latest 3.04 version. Even with the latest version of Ubuntu and on Debian Sid, xpdf is version 3.03 (which is a bit strange, because xpdf 3.04 was released in May 2014), so I cannot easily propose a backport via a PPA.

So I propose to auto-detect the version of pdftotext: it the version is over 3.04, we add the -table option ; otherwise, we don't use that option. And, in the README, we encourage to upgrade to the latest version of xpdf/pdftotext to benefit from the latest improvements.

@manuelRiel What do you think ? Do we really need to oblige ALL our users to use version 3.04 ?

If you are OK with my idea, I'll propose a PR to autodetect the version and adapt the arguments.

**Comment by manuelRiel** [comment]
The problem is that with the `-table` option documents will be parsed a little differently. So templates need to be different.

It's simple to get the static version of xpdf. No dependencies.

**Comment by alexis-via** [comment]
Ok, I understand your point. I hope that the Linux distro will update their packages soon.

**Comment by DavidGoodenough** [comment]
Debian sid currently does not package pdftotext in the xpdf package, but rather in the poppler-utils package.  Which version of that has the --table option?

**Comment by m3nu** [comment]
Debian Sid has the required package, but it's called `xpdf`, not `poppler`.

**Comment by m3nu** [comment]
I know the requirement sucks until Debian Sid is out. But as you saw in your other issue, the table-option makes a big difference for almost all invoices that use tables. (almost all invoices use tables). If we allow 2 versions, we need to redo most matching templates.

The download is just a single binary, so it's not impossible.

- Ubuntu already has the correct version. (Xenial)
- OSX also has it via Homebrew
- Debian doesn't, but will get it next year. (or can just add the bin from the website)

Do we need a better error message until then?

**Comment by DavidGoodenough** [comment]
If you go to https://packages.debian.org/sid/amd64/xpdf/filelist you will see that the pdftoxxxx utils are no longer there.  However if you do to https://packages.debian.org/sid/amd64/poppler-utils/filelist you will find them all there.

**Comment by m3nu** [comment]
Ah. They re-organized it. That should be added as note. Would be even better if they add a backports package.

**Comment by m3nu** [comment]
It will try with- and without `-table` option now and give a warning.

I guess anyone adding new templates should use the newer version to avoid them breaking in the next months.
