### ISSUE TITLE
Abolish required fields in favor of more flexibility, set required fields in template?

### ISSUE THREAD

**Issue by rlgn** [m3nu/invoice2data#111]
Here's what I got:

fields:
  Carrier: [A-Z0-9]
  Attn: \W
  Phone: \s+(\d{3}-\d{3}-\d{4})
  Fax: \s+(\d{3}-\d{3}-\d{4})?
  MC Number: \s+\d+
  "BOL #": \s+[0-9A-Z]
  Commodity: \s+[A-Za-z]
  Reference: \s[.]
  Earliest Date: \s.
  Latest Date: \s.
  Buyer: \s.
  Email: [A-Za-z\.\@\s]
  Contact: \s.
  "PO #": \s+[0-9A-Z]
  "Pick Up #": \s+[0-9A-Z]
  "Delivery #": \s+[0-9A-Z]

keywords:
  - Company Name
  - MC Number

then I get this error:

AssertionError: Missing required key in template usa.got.logistics.english.yml /Users/raulgonzalez/Documents/yml_templates. Found ['Carrier', 'Attn', 'Phone', 'Fax', 'MC Number', 'BOL #', 'Commodity', 'Reference', 'Earliest Date', 'Latest Date', 'Buyer', 'Email', 'Contact', 'PO #', 'Pick Up #', 'Delivery #']

**Comment by m3nu** [comment]
Thanks for bringing this up. It has been on my list for a while. Some background:

When `invoice2data` was first conceived I only wanted to process invoices that had all the fields I needed for accounting. So some fields, like `amount`, `date` and others are required.

Now, in 2018 people are using the library for more general purposes, which is clearly a good thing. So I think it's time to remove these "required fields" altogether or pass control over them to template authors.

For now I'll rename this issue and mark it as future enhancement. I'll take care of it in the next days after thinking about possible implications of removing required fields.

If you like you can also file  PR (should be very simple to remove those required fields) and see if anything breaks after your use case is covered.

**Comment by rlgn** [comment]
Forgive me for being ignorant with this question, but where can I find the required fields part to remove them?

**Comment by m3nu** [comment]
Good question actually. Let me find the right line.

**Comment by m3nu** [comment]
Here the relevant part: https://github.com/m3nu/invoice2data/blob/master/invoice2data/extract/invoice_template.py#L173

As you can see we are checking for `['date', 'amount', 'invoice_number', 'issuer']`

You could either rename your own fields for now or we keep those as defaults and allow overriding them in the template? That way only fully-matched documents are processed.
