### ISSUE TITLE
Save all fields to json?

### ISSUE THREAD

**Issue by msalaj** [m3nu/invoice2data#114]
Hi, how it is possible to save all fields from template to json file? Currently, only date, amount and desc is written into output file. Program write complete json to screen but it writes only three fields to json file. Thank you

**Comment by m3nu** [comment]
Good idea. We didn't allow custom fields, when the json-export was implemented. Will mark this as new enhancement. Or you can do a PR, if in a hurry.

**Comment by m3nu** [comment]
No. Unit testing means that a single functional unit is tested. So testing extraction and templates at the library level is the right thing to do. The GUI relies on this functional units and adds on them.

**Comment by duskybomb** [comment]
There are two ways to implement this
 * Adding it to template where author specifies fields he wants to dump (I am not in favour of this)
 * Using cli, with an option to dump default fields or all the fields.

**Comment by m3nu** [comment]
Let's always dump all fields. No need to specify or make a template.

**Comment by duskybomb** [comment]
Closing this one.
