### ISSUE TITLE
No handlers could be found for logger "invoice2data.main" 

### ISSUE THREAD

**Issue by jaymal** [m3nu/invoice2data#115]
Hi,
I get this message

> No handlers could be found for logger "invoice2data.main"
>False
 
after  running this 

`from invoice2data import extract_data

result = extract_data('path/to/my/file.pdf')`

What could be wrong?

**Comment by m3nu** [comment]
Couldn't reproduce this with Python 3 on MacOS.

Any relevant detail you can provide on your environment? Maybe some weird logger settings?

**Comment by m3nu** [comment]
<img width="733" alt="screen shot 2018-05-10 at 20 08 55" src="https://user-images.githubusercontent.com/3916435/39868898-20674d04-548e-11e8-82d4-31dacb741a97.png">

**Comment by m3nu** [comment]
Just tried your code in Python 2.7.14 Still works as expected.

**Comment by jaymal** [comment]
Ok I will upgrade to 2.7.12 and get back with my result.Thanks

**Comment by jaymal** [comment]
I tried python 3 and it looks fine now.Thanks
