### ISSUE TITLE
[regression] bad handling of decimal separator

### ISSUE THREAD

**Issue by alexis-via** [m3nu/invoice2data#12]
@m3nu Following your changes of January 23, the amounts with "," as decimal separator are badly converted to float. For example, pdftotext extracts "27,80" and this is converted to "2780.0" !

When I look at the code in main.py:
```
locale.setlocale( locale.LC_ALL, 'en_US.UTF-8' )
[...]
output[k] = locale.atof(res_find[0])
```

So I understand that the conversion from string to float is always done with the en_US locale, so it doesn't support dot as decimal separator. What was your idea when you wrote this code ?

My idea would be to add 2 additionnal options in the YAML files: decimal_separator and thousand_separator. We can't just define a language parameter and use it, because for example some French invoices don't respect the official french decimal separator (dot) and thousand separator (space).

**Comment by m3nu** [comment]
My idea was to set or programmatically extract the invoice language and then use that language with `locale.atof`. There may be edge cases. Feel free to add those thousand and decimal sep settings.

I'll soon do my own accounting with the lib and will discover some issues as well.

**Comment by alexis-via** [comment]
OK. I propose the following:
1) If the decimal_separator option is NOT set, fallback on the first entry of the 'languages' option and use atof() with the right locale
2) if the decimal_separator option is set, we will do the following:
a) replace the decimal separator by "."
b) remove all other separators
c) use float()

That way, we should not need the thousand_separator option, but only the decimal_separator option. We just have to make sure that we handle properly the case where "." is the thousand separator.

**Comment by m3nu** [comment]
Sounds good. I didn't find any other major issues today. Was running the lib over 6 months of invoices to match them to the corresponding bank transactions.

**Comment by alexis-via** [comment]
In the end, the implementation that I pushed in master (I forgot to cross reference with this bug report) is only step 2) of my previous comment. Why ? Because I feel that locale.atof()  is not the right solution for the following reasons:
- it is not easy to go from a 2 letter language code (fr) to a full locale (fr_FR.UTF-8)
- it is not easy to know which locale are installed on the system, to avoid a crash when you try setting a locale that is not installed
- you may want to parse an invoice in a language for which you haven't installed the locale
- the code with the decimal separator is simple and reliable
