### ISSUE TITLE
This PDF invoice doesn't match a known template of the invoice2data lib.

### ISSUE THREAD

**Issue by diezcode** [m3nu/invoice2data#16]
I have installed xpdftotext like this:
http://support.sphiderpro.eu/knowledgebase.php?article=13

then I have installed invoice2pdf like this:
https://github.com/m3nu/invoice2data

then I have installed the modul account_invoice_import in odoo8

After trying to upload some pdf like the examples pdf, I get this error:

This PDF invoice doesn't match a known template of the invoice2data lib.

**Comment by alexis-via** [comment]
Did you develop a template for the invoices of that supplier ? The available templates are available in this directory https://github.com/m3nu/invoice2data/tree/master/invoice2data/templates (and in the related subdirectories).

**Comment by diezcode** [comment]
DEBUG:invoice2data.main:number of char in pdf2text extract: 0
DEBUG:invoice2data.main:START pdftotext result ===========================
DEBUG:invoice2data.main:
DEBUG:invoice2data.main:END pdftotext result =============================
DEBUG:invoice2data.main:Testing 90 template files
ERROR:invoice2data.main:No template for invoice2data/test/pdfs/invoices-output.csv
DEBUG:invoice2data.main:{}
Traceback (most recent call last):
  File "/usr/local/bin/invoice2data", line 9, in <module>
    load_entry_point('invoice2data==0.2.13', 'console_scripts', 'invoice2data')()
  File "/usr/local/lib/python2.7/dist-packages/invoice2data/main.py", line 190, in main
    invoices_to_csv(output, 'invoices-output.csv')
  File "/usr/local/lib/python2.7/dist-packages/invoice2data/output.py", line 6, in invoices_to_csv
    with open(path, "w") as csv_file:
IOError: [Errno 13] Permission denied: 'invoices-output.csv'

**Comment by m3nu** [comment]
You're trying to recognize a CSV-file. That won't work. It's made for PDF files. You probably created that CSV when testing it earlier.

**Comment by diezcode** [comment]
I never made a csv file i any directory of invoice2data. I don't understand why I can't debug a sample pdf that is in test/pdfs


virtual-machine:/usr/local/lib/python2.7/dist-packages/invoice2data/test/pdfs$ invoice2data 2015-07-02-invoice_free_fiber.pdf --debug          pdftotext version 0.24.5
Copyright 2005-2013 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
Usage: pdftotext [options] <PDF-file> [<text-file>]
  -f <int>          : first page to convert
  -l <int>          : last page to convert
  -r <fp>           : resolution, in DPI (default is 72)
  -x <int>          : x-coordinate of the crop area top left corner
  -y <int>          : y-coordinate of the crop area top left corner
  -W <int>          : width of crop area in pixels (default is 0)
  -H <int>          : height of crop area in pixels (default is 0)
  -layout           : maintain original physical layout
  -fixed <fp>       : assume fixed-pitch (or tabular) text
  -raw              : keep strings in content stream order
  -htmlmeta         : generate a simple HTML file, including the meta information
  -enc <string>     : output text encoding name
  -listenc          : list available encodings
  -eol <string>     : output end-of-line convention (unix, dos, or mac)
  -nopgbrk          : don't insert page breaks between pages
  -bbox             : output bounding box for each word and page size to html.  Sets -htmlmeta
  -opw <string>     : owner password (for encrypted files)
  -upw <string>     : user password (for encrypted files)
  -q                : don't print any messages or errors
  -v                : print copyright and version info
  -h                : print usage information
  -help             : print usage information
  --help            : print usage information
  -?                : print usage information
DEBUG:invoice2data.main:number of char in pdf2text extract: 0
DEBUG:invoice2data.main:START pdftotext result ===========================
DEBUG:invoice2data.main:
DEBUG:invoice2data.main:END pdftotext result =============================
DEBUG:invoice2data.main:Testing 53 template files
ERROR:invoice2data.main:No template for 2015-07-02-invoice_free_fiber.pdf
DEBUG:invoice2data.main:{}
Traceback (most recent call last):
  File "/usr/local/bin/invoice2data", line 9, in <module>
    load_entry_point('invoice2data==0.2.13', 'console_scripts', 'invoice2data')()
  File "/usr/local/lib/python2.7/dist-packages/invoice2data/main.py", line 190, in main
    invoices_to_csv(output, 'invoices-output.csv')
  File "/usr/local/lib/python2.7/dist-packages/invoice2data/output.py", line 6, in invoices_to_csv
    with open(path, "w") as csv_file:
IOError: [Errno 13] Permission denied: 'invoices-output.csv'

**Comment by m3nu** [comment]
You also have an outdated pdftotext version. We need the table-feature, which is only available in recent versions. I suggest you update first.

**Comment by diezcode** [comment]
I have this one : http://www.foolabs.com/xpdf/download.html
for linux version 3.04. Where is the newest?

**Comment by m3nu** [comment]
No you don't. You are using the Ubuntu-supplied `pdftotext version 0.24.5`.

Closing this since it's an installation issue.

**Comment by trinanda** [comment]
I'm also facing this issue.
How did you solve this issue @diezcode ?

**Comment by NayanMogra** [comment]
hi, I was also facing this issue that invoice doest match,
Then I found out that issue is occurring due to the library can't able to find some of the keywords that you might mention in yml file in my case library cant able to find the issuer name though it was on top of pdf,
DEBUG:invoice2data.main:START pdftotext result ===========================
DEBUG:invoice2data.main: 
after this line, you can able to see your pdf data so check from here whether you are getting all data as pdf.
