### ISSUE TITLE
Allow custom data fields to be retrieved

### ISSUE THREAD

**Issue by sylvaingd** [m3nu/invoice2data#17]
Would it be possible to improve French EDF Entreprises template to retrieve energy consumption?

**Comment by m3nu** [comment]
Probably. We would need to allow custom invoice attributes in the config files. I don't have an EDF invoice ready, so someone needs to share their invoice file with me. You can replace all sensitive information with a PDF editing software? @sylvaingd

**Comment by sylvaingd** [comment]
Any idea to edit the invoice PDF file? (except Adobe Acrobat) because I can provide such a file but I would like to modify sensitive information.

**Comment by m3nu** [comment]
There are many software packages, I would imagine.  You can also just send it to `submit [at] t.snapdragon.cc` and I'll remove the personally identifiable data for you. @sylvaingd

**Comment by alexis-via** [comment]
@sylvaingd FYI, if you use the services of EDF Entreprise, they propose their invoices in XML format following the UBL 2.0 standard (https://www.edf.fr/entreprises/contrat-et-facture/votre-facture/flux-electronique-de-facturation-flux-edi), and this XML file has all the information about consumption. The technical specs are here https://entreprises.edf.com/fichiers/fckeditor/Commun/Entreprises/pdf/Guide%20technique%20facture%20EDF%20en%20XML%20V1.2.pdf

**Comment by m3nu** [comment]
This is already possible. Mentioned it in the new tutorial now.
