### ISSUE TITLE
Add Tutorial for template creation and best practice

### ISSUE THREAD

**Issue by DavidGoodenough** [m3nu/invoice2data#18]
and not really understanding how to go about it.  A data file I am trying to work with looks like:-
(As this is a public forum, I have changed the supplier name to "Supplier" and the customer name to "Customer")
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Supplier Name
Carterton
Oxfordshire
OX18 3EZ

Invoice

Page 1

Tel:- (01993) xxxxxx Fax: - (01993) xxxxxx
Email:- accounts@supplier.co.uk
VAT Reg No: xxx xxxx xx
Customer
Nr Lechlade, Glos
GL7 3QS

55574
11/05/2016

BPOO1

Quantity Details
1.00 Job 25326. To supply only 6no M12x150
8.8 bzp bolts as required.

Terms strictly 28 days from date of invoice
Goods remain the property of Supplier
until payment has been received in full.
BACS Details (HSBC)
Sort Code 40-16-46
Account 11055860

Unit Price

Net Amt

VAT %

VAT

4.70

4.70

20.00

0.94

Total Net Amount

4.70

Carriage Net

0.00

Total VAT Amount

0.94

Invoice Total

5.64

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Most of the bits of text seem to be on separate lines, so I have to tell it to step over whitespace, or does it do it for me.

Is there a description of the pattern matching formats?

Thanks in advance

**Comment by alexis-via** [comment]
In this case, it is probably easier to activate the option "remove_whitespace" in your template. See for example the template "de.ovh.yml" in the master branch.

The pattern matching format is a regexp.

**Comment by DavidGoodenough** [comment]
I tried that, but if you look at the data there are places where there are consecutive numbers, with remove_whitespace they get concatenated so I can not parse them.  

What I do not understand is how the regex is applied.  How much of the incoming dataset is scanned for each regex?  Also do the regex's have to be in order, i.e. sequentially down the output from pdftotext?

It would be really useful to have a worked example of taking an invoice, and then building a template.  Could one be put in the wiki?

**Comment by m3nu** [comment]
I fully agree there should be a tutorial on writing the first template.

To help, you need to attach the PDF file as well.

Are you using it without `--table` option? Without table option the above may happen and lines are broken by table cells.

**Comment by DavidGoodenough** [comment]
I can not send the the original as that would require the agreement of the sender (it has their company name, full address and phone and email details).  I will try to generate one which has dummy data in it and attach it to this thread.

I am using the version of of pdftotext with the -table option - I downloaded the binary directly.

**Comment by m3nu** [comment]
I see. You can redact the company name with some PDF editing software (Fox, Acrobat, Illustrator).

Some whitespace is not an issue for regex. Just needs to be added.

**Comment by DavidGoodenough** [comment]
Here is an annonomised PDF.
[sample-invoice.pdf](https://github.com/m3nu/invoice2data/files/261414/sample-invoice.pdf)

**Comment by m3nu** [comment]
Thanks. From what I can see the lines come out correctly with the `-layout` or `-table` option.

```
Item Description                                                                   Qty Price  Per  Total               VAT Rate

1 Duracell AAA Batteries - Multi -Pack of 8 (5+3)                                  1.00 3.32  ea          3.32         0.66         20.00
                                                                                              ea          4.15         0.83         20.00
2 Duracell AA Batteries - Multi-Pack of 8 (5+3)                                    1.00 4.15  ea        11.24          2.25         20.00
                                                                                              ea        10.11          2.02         20.00
3 TIMco ADDAX V5 IMPACT BIT SET WITH QUICK RELEASE 25mm - MIXED 10 PIE1.C0E0 SET 12.49        ea          6.24         1.25         20.00
                                                                                              ea          6.27         1.25         20.00
4 HILTON BANKS GAFFER TAPE GREY 50MM X 50MTR                                       3.00 3.75  ea          7.43         1.49         20.00

5 TIMBER DRIVE 7X150mm P/P 25                                                      1.00 6.93

6 TIMBER DRIVE 7X200mm P/P 10                                                      1.00 6.97

7 SPAX-S 5.0 X 40 BOX OF 200                                                       1.00 8.26

  Payment terms are strictly net monthly                                                           Total Amount                     £ 48.76
Subject to our terms and conditions of sale. Further copies available on request.                  Total VAT                         £ 9.75
                                                                                                   Invoice Total
                                                                                                                                    £ 58.51
```

I'll work on adding the flexible fields and tutorial today. Then we can see if you still have issues with those lines.

**Comment by DavidGoodenough** [comment]
Excellent, the tutorial will I am sure be very useful both to me and other users of your package.
I do not know if you were aware of it, but Akretion (see http://www.akretion.com/blog/akretions-christmas-present-for-the-odoo-community) recently published a plugin for Odoo (formerly OpenERP) which reads PDF invoice directly into Odoo, thus saving typing.  They use your code to do this.
So it is to be expected that lots of people will need to know how to write templates for the invoices they receive as not everyone will be sending invoices using  ZUGFeRD - although they really should.

**Comment by alexis-via** [comment]
@DavidGoodenough I am the author of the Odoo module and of the blog post on Akretion's website. Are you developping templates to use them with Odoo ? I would be very happy about that, because I haven't seen many users of my Odoo invoice import modules so far...

**Comment by DavidGoodenough** [comment]
I have spent 40 years in the IT industry, and I have recently returned to the family farm.  I am doing most of the paperwork.  We are trying to get into precision farming, but also have to do the accounts. 

Oddly farmers rarely raise invoices, we recieve lots, but when we sell things we get the bill we would have issued from our customer because they weigh things, and do quality grading to work out the price.  So I spend much of my life retyping other people's invoices (both in and out, the self billing was something I was going to try to add myself and then feed back to you), and when I saw your stuff I was really interested.  

My biggest challenge is that I am running Odoo on a Cubieboard (for a 3 user system its wonderful), but getting the right version of wkhtmltopdf and come to that pdftotext on armhf is not easy.  Currently poppler-utils is only built for amd64 on sid.  I have sent the maintainer a message asking for an armhf version, but no reply yet.

I did have a little problem installing your code, because it does not seem to have been pulled into OCA yet.  Then I learned about the git pr command so it is a bit easier.  Is there a reason why your pull request has not been answered?

**Comment by m3nu** [comment]
Did you try compiling xpdf from [source](http://www.foolabs.com/xpdf/download.html)? There are only 3 dependencies. I have some Arm-boxes too and could try if it doesn't work for you.

**Comment by m3nu** [comment]
Compiling was really simple. It will build `pdftotext` even without some of the deps installed and skip some other tools. Will look at the tutorial, extra fields, CI and warning on xpdf version today.

**Comment by m3nu** [comment]
New tutorial to be found [here](https://github.com/m3nu/invoice2data/blob/master/TUTORIAL.md).

**Comment by m3nu** [comment]
PS: @alexis-via: I refactored most template processing into a new class to reduce the chaos in future versions. The high-level stuff is unchanged. If I broke something for you, let me know.

**Comment by OmriRoames** [comment]
Hi, I've just cloned the repo and I'm trying to run it from source. I'm guessing `python invoice2data/main.py --help` should be the way to run it. However I'm getting an ImportError:

Traceback (most recent call last):
  File "invoice2data/main.py", line 9, in <module>
    import invoice2data.in_pdftotext as pdftotext
ImportError: No module named invoice2data.in_pdftotext

Which is not really surprising since main.py is part of invoice2data so it can't import itself.

Any suggestions? 

Cheers

**Comment by R470R** [comment]
Sir @m3nu , tutorial link is down, would be really useful

**Comment by m3nu** [comment]
Tutorial is linked on the frontpage @R470R . Please check there instead of this old issue.
