### ISSUE TITLE
--template-folder dir, so be an addition to the standard templates, not a remplacement

### ISSUE THREAD

**Issue by alexis-via** [m3nu/invoice2data#19]
I have added support for --template-folder when using invoice2data via Odoo. But, when we use  --template-folder xxx, the templates are read from the xxx directory, but the native templates of invoice2data are ignored.

I think that, when we use --template-folder xxx, these templates in xxx should be used in addition to the native templates. What do you think ? If you agree, I can try to find time to submit a patch.

**Comment by m3nu** [comment]
Templates are just read into a list from a folder. That can happen multiple times of course.

I don't have a strong opinion. It can read the built-in templates all the time.

Or multiple ``--template-folder`` switches to add multiple folders?

**Comment by m3nu** [comment]
Could still be useful to exclude the built-in templates. Testing, speed, etc? But also don't want to add too many pointless options because of it.

**Comment by alexis-via** [comment]
yes, we could have an option to exclude built-in templates. I propose 2 options:
--template-folder /my/private_template_folder : will use the private template folder and the built-in template folder -> that will be the most common use
--exclude-built-in-templates : must be used in conjonction with --template-folder : will use the private folder and ignore the built-in template folder
I don't think we need to have support for multiple private templates, as we scan the subdir of this private template (and we should follow symlinks), so users can get their templates organised within the private folders or use symlinks to point to other directories.

**Comment by m3nu** [comment]
That's two more arguments and the same I had in mind.

You want to implement it or assign it to me? I recently refactored the lib to be more object-oriented. Should be quick to add this option. Just needs some lines in `main.py` I think.

**Comment by alexis-via** [comment]
I am very busy with other developments in the Odoo community at the moment, so I won't do it in the short term. If you have some time to do it, that would be great. Otherwise, I'll do it myself, but not in the short term.

**Comment by m3nu** [comment]
Sure. I'll take care.

**Comment by alexis-via** [comment]
@m3nu Thanks ! I think our users should be happy now : they can benefit from the standard templates AND develop their own private template without problems.
