### ISSUE TITLE
Raise exception when date parsing fails

### ISSUE THREAD

**Issue by alexis-via** [m3nu/invoice2data#21]
On this line of code:
https://github.com/m3nu/invoice2data/blob/master/invoice2data/template.py#L137

when date parsing fails, we log an error and we return None. But that's a problem when invoice2data is used by another software as a python lib because the software cannot display a good error message "date parsing fails ..." to the user.

**Comment by m3nu** [comment]
It can throw an exception in addition. This will propagate up to Odoo, right? If the date parsing fails there is not much to be done. Or ignore it and continue without date?

**Comment by alexis-via** [comment]
I prefer to log (as we do today) and raise an exception (I don't like if it fails silently).

**Comment by m3nu** [comment]
ok. Let's add this when we next touch the code.

**Comment by m3nu** [comment]
I changed the code a bit to only return a result, when required fields ('date', 'amount', 'invoice_number', 'issuer') are matched in the `v2` branch.
