### ISSUE TITLE
AttributeError 

### ISSUE THREAD

**Issue by splifter** [m3nu/invoice2data#28]
Hey guys,

i'm trying to create a template for an invoice with the following setup:

>DEBUG:root:Date parsing: languages=[] date_formats=[]
>DEBUG:root:Float parsing: decimal separator=,
>DEBUG:root:keywords=['DeutschePostAG']
>DEBUG:root:{'remove_whitespace': True, 'remove_accents': False, 'lowercase': False, 'currency': >'EUR', 'date_formats': [], 'languages': [], 'decimal_separator': ',', 'replace': []}
>DEBUG:root:field=amount | regexp=Rechnungsbetrag(\W+)?\(inklusive(\W+)?Umsatzsteuer\)(\W+)?(\d+\.\d+\,\d+)(\W+)?EUR

The result is:
> DEBUG:root:res_find=[('', '', '', '30.277,88', '')]

But i get following error:
> Traceback (most recent call last):
 > File "/usr/local/bin/invoice2data", line 11, in <module>
    > sys.exit(main())
>  File "/usr/local/lib/python3.6/site-packages/invoice2data/main.py", line 84, in main
>    res = extract_data(f.name, templates=templates)
>  File "/usr/local/lib/python3.6/site-packages/invoice2data/main.py", line 40, in extract_data
>    return t.extract(optimized_str)
>  File "/usr/local/lib/python3.6/site-packages/invoice2data/template.py", line 151, in extract
>    amount_pipe = res_find[0].replace(self.options['decimal_separator'], '|')
> AttributeError: 'tuple' object has no attribute 'replace'

Thanks for your help.

**Comment by m3nu** [comment]
Can you post the template you made, so we can see the settings? @splifter

**Comment by splifter** [comment]
Sure:
`
issuer: DHL
keywords:
- DeutschePostAG
fields:
  date: Rechnungsdatum(\W+)?(\d{2}(\.|-)\d{2}(\.|-)\d{4})
  amount: Rechnungsbetrag(\W+)?\(inklusive(\W+)?Umsatzsteuer\)(\W+)?(\d+\.\d+\,\d+)(\W+)?EUR
  invoice_number: Rechnungsnummer(\W+)?(\d{10})
options:
  remove_whitespace: true
  currency: EUR
  decimal_separator: ','
`

**Comment by m3nu** [comment]
Your regexes have too many capturing groups. @splifter . You can only have one, I think. Example:

`amount: Крайнасума:(\d+\.\d+)USD`

Hope this helps. We should do a template authoring tutorial at some point.
