### ISSUE TITLE
read_template codec error

### ISSUE THREAD

**Issue by Bummibaer** [m3nu/invoice2data#32]
Hi,

I 've started and get the following error with 
cloudns.yml ( I think from russian letters):

I 've no experience with Python. How can I switch the locale?

My Environment:
Win10 64 Home
Active Perl 3.6

> C:\Python36\lib\site-packages\invoice2data-0.2.53-py3.6.egg\invoice2data\templates 	 com.cloudns.yml
Traceback (most recent call last):
  File "C:\Users\PapaNetz\.p2\pool\plugins\org.python.pydev_5.7.0.201704111357\pysrc\pydevd.py", line 1546, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\PapaNetz\.p2\pool\plugins\org.python.pydev_5.7.0.201704111357\pysrc\pydevd.py", line 982, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\PapaNetz\.p2\pool\plugins\org.python.pydev_5.7.0.201704111357\pysrc\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\PapaNetz\git\invoice2data\invoice2data\main.py", line 96, in <module>
    main()
  File "C:\Users\PapaNetz\git\invoice2data\invoice2data\main.py", line 80, in main
    templates += read_templates(pkg_resources.resource_filename('invoice2data', 'templates'))
  File "C:\Python36\lib\site-packages\invoice2data-0.2.53-py3.6.egg\invoice2data\template.py", line 39, in read_templates
    tpl = ordered_load(open(os.path.join(path, name)).read())
  File "C:\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 53: character maps to <undefined>

**Comment by m3nu** [comment]
Interesting. Python 3 shouldn't give Unicode errors. We test on 3.6 as well and didn't happen so far.

If you find a workaround, do let us know.

**Comment by Unhurdof1** [comment]
Hello,
I was also getting this error and resolved it by changing the line 38 in template.py to:
 tpl = ordered_load(open(os.path.join(path, name)**,encoding="utf8"**).read())

on my computer (windows 8) template.py is located here: C:\Users\Max\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\invoice2data

Hope this helps.

**Comment by sagaciousnisha3** [comment]
Hi I tried your suggestion and got this Error on every available template. Would be helpful if you have any solutions.
C:\Python35\lib\site-packages\invoice2data\template.py:38: ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\Python35\\lib\\site-packages\\invoice2data\\templates\\com.apps4rent.yml' mode='r' encoding='utf8'>
  tpl = ordered_load(open(os.path.join(path, name),encoding="utf8").read())

**Comment by m3nu** [comment]
That's a warning related to the way we read template files. I just replaced it with `with ...` constructs. Should be solved now.

**Comment by WSPeng** [comment]
Strangely I still get this warning Unicode error...

**Comment by duskybomb** [comment]
It is an error with pip relating to text encoding on Windows https://github.com/pypa/pip/issues?q=is%3Aopen+is%3Aissue+UnicodeDecodeError+setup.py 

The only workaround is using python2.

I think this issue can be closed now.

**Comment by WSPeng** [comment]
I tried in two windows and a Ubuntu computer, and only ubuntu one works, as expected.
I tried solution provided by sagaciousnisha3, it works, but I get "
WARNING:root:regexp for field invoice_number didn't match 
ERROR:root:Unable to match some fields:
" for two example pdf out of four.

**Comment by duskybomb** [comment]
@WSPeng if you want to use it in windows (accurately), you have to use python2. Can you try and confirm?

**Comment by WSPeng** [comment]
@duskybomb I installed python 2.7.14 and try it, it gives same error as python3.6 (can't extract data from QualityHosting.pdf and PAYPAL ENVATO MKPL EN 4029357733 AU.pdf)
Here is the detail:
>>> from invoice2data import extract_data
>>> r1 = extract_data('2014-05-07 Invoice 30064443 from QualityHosting.pdf')
WARNING:root:regexp for field invoice_number didn't match
ERROR:root:Unable to match some fields:
>>> r2 = extract_data('2014-08-03 SALES Amazon Web Services  aws.amazon.coUS.pdf')
>>> r3 = extract_data('2015-01-29 PAYPAL ENVATO MKPL EN 4029357733 AU.pdf')
WARNING:root:regexp for field amount didn't match
WARNING:root:regexp for field amount_untaxed didn't match
WARNING:root:regexp for field date didn't match
WARNING:root:regexp for field invoice_number didn't match
ERROR:root:Unable to match some fields:
>>> r4 = extract_data('2015-07-02-invoice_free_fiber.pdf')
>>> r5 = extract_data('Flipkart Invoice.pdf')

The information about python I used:
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by duskybomb** [comment]
I think this issue has been resolved by #99 
We should close this.

**Comment by m3nu** [comment]
Let's hope so. Closing.
