### ISSUE TITLE
 Allow the user to choose the CSV file

### ISSUE THREAD

**Issue by maethor** [m3nu/invoice2data#33]
I think the CSV output should be a command argument, to allow the user to choose where to put it and, if not argument is given, to not generate it.

**Comment by m3nu** [comment]
Agreed.

**Comment by duskybomb** [comment]
@m3nu Can I work on this issue?

**Comment by m3nu** [comment]
Sure. Small change. You already did a PR (#68), right? See my comment on the code [there](https://github.com/m3nu/invoice2data/pull/68/files#r168760750).

**Comment by duskybomb** [comment]
@m3nu made the changes in the code for PR(#68) if you merge it, I can make a PR for this issue.

**Comment by rsenwar** [comment]
@m3nu I am also working on the same issue, ( #67 ) Made some more changes to the PR.

**Comment by m3nu** [comment]
Let's not overdo it for a 2-line change, folks. There are harder/more interesting problems to work on.
