### ISSUE TITLE
Could not find a version that satisfies the requirement dateparser (from invoice2data==0.2.59)

### ISSUE THREAD

**Issue by sagaciousnisha3** [m3nu/invoice2data#43]
While installing invoice2data0.2.59 I got the error 
"Could not find a version that satisfies the requirement dateparser (from invoice2data==0.2.59)". I get the same with PDFminer.six. When I remove them from the requirements file it works. Have I missed out any part of the installation?

**Comment by m3nu** [comment]
`dateparser` is one of the requirements. It should install fine. I just tried it. [Details here](https://pypi.python.org/pypi/dateparser).

**Comment by sagaciousnisha3** [comment]
Thanks for answering. I found the issue. I was installing it offline

**Comment by m3nu** [comment]
Good your found the issue. Closing this issue.
