### ISSUE TITLE
Processing a folder

### ISSUE THREAD

**Issue by sagaciousnisha3** [m3nu/invoice2data#45]
I tried to process a folder of invoices to a single output CSV using command line but it gives me an error
"invoice2data: error: argument input_files: can't open '*.pdf': [Errno 22] Invalid argument: '*.pdf'"
I'm using windows 10. 

The command line I used is 
C:\Users\IT\Desktop\test>invoice2data *.pdf
All my PDF are in the folder test.
Please help me resolve?

Code used:

'''
Created on 15 Aug 2017
Code used:
@author: it
'''
import test_ui
import invoice2data
import logging
from PyQt5 import QtWidgets, QtGui, QtCore
import subprocess
import os
from invoice2data.main import extract_data
        
class MainWindow(QtWidgets.QMainWindow, test_ui.Ui_MainWindow):
    def __init__(self,parent=None):
        super(MainWindow,self).__init__(parent)        
        self.setupUi(self)
        
    
if __name__ == "__main__":
    
    os.chdir("C:\\Users\\it\\Desktop\\test")
    os.system("cmd.exe /c invoice2data *.pdf")

**Comment by rsenwar** [comment]
try using ./*.pdf

**Comment by m3nu** [comment]
You are running a Python script from another Python script via the shell? why not use the library directly? Or a real shell script to pass each file.
