### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by michelpf** [m3nu/invoice2data#46]
Despite I downloaded the Poppler for Windows, I receive same error messages:

  File "C:\Python\Python36\lib\site-packages\invoice2data\in_pdftotext.py", line 19, in to_text
    raise EnvironmentError('pdftotext not installed. Can be downloaded from https://poppler.freedesktop.org/')
OSError: pdftotext not installed. Can be downloaded from https://poppler.freedesktop.org/

Any clues?

**Comment by michelpf** [comment]
Sorry, it was not on Path... :( It worked

**Comment by saisivasriram** [comment]
Can you explain it clear on what you did, As I am also facing the same error in UBUNTU
