### ISSUE TITLE
How to handle Value which are below mentions 

### ISSUE THREAD

**Issue by DebayanChakraborty** [m3nu/invoice2data#53]
There are invoices where the mention and value are paired as 
INVOICE #
xxxxxxxxx  (x= any digit 0-9)
and there may be many other noise in front of this . Can Invoice2data handle this ? 
My regex is working but not matching  

regex used is INVOICE\s#\s+.*?\s+(\d+)
this works in regex101 nd matches with two groups however this fails to fetch the data ...

How can one handle these scenarios

**Comment by rsenwar** [comment]
you can try \d{frequency of x}
