### ISSUE TITLE
Extract production information from line between FirstLine and LastLine of one product

### ISSUE THREAD

**Issue by isfando** [m3nu/invoice2data#55]
example of one product details in invoice given below

Serla Kostea Siivousliina 32 kpl
221443 92537  1 TU 14.160 TU  24 0.00  
   /     14.16  

How should i extract middle line info
I have written a regular expression for FirstLine which cover the first two lines in regex101 editor but it wont work with the extract_lines() function because extracts text line by line.

firstline: (?P\<desc\>.+?)\s+(\d+)\s+(\d+)\s+(?P\<qty\>\d+\s+TU)\s+(?P\<unitprice\>\d+.\d+(:?\s+TU))\s+(?P\<taxpercent\>\d+(\.\d+)?)\s+(?P\<discount\>\d+\.\d+)

![firstline](https://user-images.githubusercontent.com/5813617/33556604-2c229c40-d90d-11e7-8baa-2e9222a9f5a4.JPG)

lastline: \s+\/\s+(?P\<totalamount\>\d+\.\d+)

![lastline](https://user-images.githubusercontent.com/5813617/33556660-561bd25a-d90d-11e7-8806-fffb8c59eb56.JPG)

**Comment by isfando** [comment]
@hbrunn 
Can you have a quick look at it. I have explained the problem to the best of my abilities

**Comment by hbrunn** [comment]
you need to produce a line regex that matches the middle lines, but not the last line. And hook your expressions to the begin/end of line. Check https://github.com/m3nu/invoice2data/blob/master/invoice2data/templates/de.qualityhosting.yml as an example

**Comment by isfando** [comment]
**My input string is**
Serla Kostea Siivousliina 32 kpl
221443 92537 1 TU 14.160 TU 24 0.00
/ 14.16

**I made my firstline regex match the middle line and i successfully get it but i miss the description in the first line**
line: ^\s*(?P<desc>.+)$
firstline:(\d+)\s+(\d+)\s+(?P<qty>\d+\s+TU)\s+(?P<unitprice>\d+.\d+(:?\s+TU))\s+(?P<taxpercent>\d+(.\d+)?)\s+(?P<discount>\d+.\d+)
lastline: \s+/\s+(?P<totalamount>\d+.\d+)


**Result Acheived**
{'qty': '1 TU', 'discount': '0.00', 'taxpercent': '24', 'unitprice': '14.160 TU', 'totalamount': '14.16'}

**Results Expected**
{'desc': 'Serla Kostea Siivousliina 32 kpl','qty': '1 TU', 'discount': '0.00', 'taxpercent': '24', 'unitprice': '14.160 TU', 'totalamount': '14.16'}

The result of 'desc' group is missed

I tried to learn it from the example you provided but i could not get a grasp

**Comment by isfando** [comment]
@hbrunn 


**My input string is**
Serla Kostea Siivousliina 32 kpl
221443 92537 1 TU 14.160 TU 24 0.00
/ 14.16

**I made my 'firstline:' regex match the middle line and i successfully get it but i miss the description in the first line**
line: ^\s*(?P\<desc\>[\w ]+)$
firstline:(\d+)\s+(\d+)\s+(?P\<qty\>\d+\s+TU)\s+(?P\<unitprice\>\d+.\d+(:?\s+TU))\s+(?P\<taxpercent\>\d+(.\d+)?)\s+(?P\<discount\>\d+.\d+)
lastline: \s+/\s+(?P\<totalamount\>\d+.\d+)


**Results Acheived BUT DONT KNOW HOW**
{'desc': 'Serla Kostea Siivousliina 32 kpl','qty': '1 TU', 'discount': '0.00', 'taxpercent': '24', 'unitprice': '14.160 TU', 'totalamount': '14.16'}


I have successfully got what i wanted but i dont know how. With hit and trial
Can you take a minutes to explain so i can handle more cases like this in future
