### ISSUE TITLE
How to extract from a particular position using regex ?

### ISSUE THREAD

**Issue by VarshiniRaman** [m3nu/invoice2data#59]
![shipto](https://user-images.githubusercontent.com/35999362/35625002-95a34d44-0645-11e8-93b9-cf9ef35ad498.png)
I want to extract the Ship To details alone, but I am able to extract only the entire text from Ship to till the end of the specified text or line using (SHIP TO :(.*\n){5}) expression.

**Comment by m3nu** [comment]
A good regex tutorial will help. Out of scope here.
