### ISSUE TITLE
Adding tesseract to OCR and extract

### ISSUE THREAD

**Issue by akshay772** [m3nu/invoice2data#61]
I am trying to get this module to work with image invoices too with pytesseract. 
But I am facing a problem that the structure is not preserved when image is OCRed. 

Hence some info is lost and I can't run regex over it. Lets say, I have a image of invoice of amazon. That have 2 orders that I bought(each order description can be 2 or more lines), for each order there is a corresponding amount attached to it within the same row. So after applying OCR over it, it prints the 1st line of 1st order + price + 2nd line of 1st order ... and so on.

I have tried applying the image to data options to retrieve coordinates to put the text in separate boxes. But in this approach too, for different invoices will have different spacing I am not able to make proper boxes. 

Can anyone suggests some method of recognizing such images?

**Comment by m3nu** [comment]
OCR is a bit challenging. I experimented with it some years ago but ran into the same issues. If text recognition is better now, the first thing I'd try is to remove white space.

**Comment by rsenwar** [comment]
@akshay772  You can try finding regex pattern by removing white spaces by adding 'remove_whitespace: true' under 'options' attribute for your template.

**Comment by m3nu** [comment]
We are back to supporting different input methods in the upcoming `v2` branch. Tesseract is one of them. Not really tested yet, but I'll close this issue for now.
