### ISSUE TITLE
Extraction of field from invoice

### ISSUE THREAD

**Issue by andreipetrescu95** [m3nu/invoice2data#69]
Hello, i was wondering if there is any way that I could extract the name or the address from the ”buyer” field from this invoice using invoice2data.
[inv4.pdf](https://github.com/m3nu/invoice2data/files/1730924/inv4.pdf)

**Comment by m3nu** [comment]
Not sure whether we support custom fields already. If not, it's a planned feature.

The current use case is that you are always the buyer and the seller is given by the template being used.

**Comment by m3nu** [comment]
You can already extract any fields you like, as long as you can put them in a regex. See the docs [here](https://github.com/m3nu/invoice2data/blob/master/TUTORIAL.md#fields).
