### ISSUE TITLE
Refactor for better modularity

### ISSUE THREAD

**Issue by m3nu** [m3nu/invoice2data#72]
I took a first shot at restructuring to make the three processing steps more modular. I see three main steps that have interchangeable modules. 

1. `input`: Read plain text from somewhere. Could be a PDF, website, ERP system. Currently only `pdftotext` works.
2. `extract`: Get fields using templates. I moved the line extraction feature into a subclass. There could be other subclasses for different ways to find fields. Templates should be able to choose from multiple extraction plugins. Still needs some refactoring to achieve this.
3. `output`: Save results to a file or somewhere else. Currently supports `csv`. `json` will be added soon.

Those options can be combined from the CLI tool

`invoice2data --input-reader tesseract --output-format json FILE.PDF`

or the main `extract_data` function

`extract_data(invoicefile, input_module=pdftotext):`

I tried to keep it all backwards-compatible. The few tests we have still work.

Please let me know your feedback and then we'll merge the refactoring. Code is in a [separate branch called `v2`](https://github.com/m3nu/invoice2data/tree/v2). @hbrunn @alexis-via @duskybomb @rsenwar 

Other changes done or planned (todo list):

- [x] Add developer guide to help people start quickly. [DEVELOP.md](https://github.com/m3nu/invoice2data/blob/v2/DEVELOP.md)
- [x] Organize different ways to extract fields as subclasses.
- [x] Allow templates to choose from different plugins/extraction steps.
- [x] More tests. Especially for CLI tool. #8 
- [x] Add JSON output module. #34 
- [ ] Update Python versions we test on. Currently up to 3.6
- [ ] Add new contributors to README file.

**Comment by rsenwar** [comment]
@m3nu Exactly was I was thinking of !, we can have have separate folder for every layer. and then different functions/modules for each action within that layer. I think we should first work on v2 branch and make it smooth, then merge it to master branch.

**Comment by m3nu** [comment]
That's the plan. PRs welcome. Especially for the JSON export. I'll look into making the processing stuff more flexible.

**Comment by rsenwar** [comment]
Json export functionality added and some other errors removed and some filenames changed, have a look at my PR #73

**Comment by m3nu** [comment]
You're on fire @rsenwar . Will look into it tomorrow.

**Comment by hbrunn** [comment]
can't do a full review right now, but this looks very good on first glance!

**Comment by m3nu** [comment]
Merged all your contributions @rsenwar and @duskybomb .

Also finished the plugin system, which should be very extensible now.

Tasks left before `v2` can be merged:

### Tests for command line tool
The most common way to test CLI tools with various arguments seems to override the `argparser` and replace it during testing. See the 2 links:

- http://dustinrcollins.com/testing-python-command-line-apps
- https://stackoverflow.com/questions/18160078/how-do-you-write-tests-for-the-argparse-portion-of-a-python-module

### Update `README.md`
This is the first thing people see. At a minimum we need:
- Proper documentation of all CLI arguments. Similar to `invoice2data -h`

Nice to have:
- Maybe a GIF that shows how data is pulled from a PDF.

**Comment by m3nu** [comment]
When we are done here, our 2 newest contributors should be added to the `README` as well of course.

**Comment by m3nu** [comment]
Since people are still filing PRs against the old branch, I suggest to merge `v2` on Monday.

On a different note there is still a demand for mentors to guide students working on this project over the Google Summer of Code. @hbrunn and @alexis-via would be suitable. To extend your own features and implement new features suggested in #75 . Details [here](https://wiki.debian.org/SummerOfCode2018/Projects#SummerOfCode2018.2FProjects.2FExtractingDataFromPDFInvoicesAndBills.Extracting_data_from_PDF_invoices_and_bills_for_financial_accounting).

**Comment by hbrunn** [comment]
great features, and thanks for the invitation. But I can't commit a [significant amount of time](http://write.flossmanuals.net/gsoc-mentoring/what-makes-a-good-mentor) the coming months, so I'll have to abstain.

**Comment by duskybomb** [comment]
@m3nu how to Update Python versions we test on?

**Comment by m3nu** [comment]
Has to be done in tox and circleCI. I'm not fully sure how or whether it's supported. Will check it out myself first.

**Comment by m3nu** [comment]
Generally done.
