### ISSUE TITLE
ResourceWarning: unclosed file

### ISSUE THREAD

**Issue by duskybomb** [m3nu/invoice2data#77]
I was running tests on CLI and received this warning
```
/home/harshit/gsoc/gsoc-invoice2data/invoice2data/invoice2data/test/test.py:36: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/harshit/gsoc/gsoc-invoice2data/invoice2data/invoice2data/test/pdfs/2014-08-03 SALES Amazon Web Services  aws.amazon.coUS.pdf' mode='r' encoding='UTF-8'>
  self._run_test_on_folder(folder)])
/home/harshit/anaconda3/lib/python3.6/unittest/case.py:605: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/harshit/gsoc/gsoc-invoice2data/invoice2data/invoice2data/test/pdfs/2014-08-03 SALES Amazon Web Services  aws.amazon.coUS.pdf' mode='r' encoding='UTF-8'>
  testMethod()
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK

 ```
The test script is: 

https://github.com/duskybomb/invoice2data/blob/patch-1/test.py

**Comment by m3nu** [comment]
We probably open the pdf files incorrectly somewhere.  Just fixed this for the template files, but didnt fix it for pdfs.

You can try to fix it or open an issue for it pasting the error message.

**Comment by m3nu** [comment]
Actually you already opened an issue. So thats done.

**Comment by m3nu** [comment]
This is likely related to `Argparser` opening the input files. We shouldn't have `Argparser` open any files.

**Comment by duskybomb** [comment]
This one is not because of `Argparser`, because the warning is while testing from `test_extraction.py` and we don't use `Argparser` there

**Comment by m3nu** [comment]
Closing since it wasn't a problem for a while. Maybe fixed.
