### ISSUE TITLE
Export to UBL or EDIFACT

### ISSUE THREAD

**Issue by cjlcarvalho** [m3nu/invoice2data#84]
Hello, 

I want to start collaborating in this project. As I looked at https://github.com/m3nu/invoice2data/issues/75, there is an idea of new feature that involves export to UBL.

I want to know if there are enough benefits to this feature or if I should collaborate in other demand that is more important. 

Any advice or information about the UBL feature will be appreciated.

**Comment by m3nu** [comment]
Before you start, please look into 

- the business case. Is this format used and supported by other tools?
- documentation. Where is the format documented? Are the specifications stable or changing?
- new dependencies. Any new libraries needed?

**Comment by m3nu** [comment]
You still wanna work on this @cjlcarvalho ?

**Comment by cjlcarvalho** [comment]
Yes, I'll try to start during the next week. I'm currently involved with some university appointments.

**Comment by m3nu** [comment]
[EDIFACT](http://www.unece.org/trade/untdid/d02b/trmd/invoic_c.htm) is another established standard to exchange machine-readable invoice data. Let's look into this as well.

**Comment by m3nu** [comment]
We'll implement this via another project that uses `invoice2data` internally. So I'm closing it here.
