### ISSUE TITLE
isuue of main.py

### ISSUE THREAD

**Issue by utsav666** [m3nu/invoice2data#89]
how do I post output to particular endpoint from main.py.....we are trying the file but it's not working

**Comment by m3nu** [comment]
"how do I post output to particular endpoint from main.py.....we are trying the file but it's not working"

**Comment by m3nu** [comment]
Can you be a bit more specific? I'm not sure what "endpoint" means here. This term generally refers to networked APIs.

**Comment by duskybomb** [comment]
I think he is asking 'how to send output to a specific directory?'. If yes, do this 
```
invoice2data --output-format csv --output-name mydirectory/invoice.csv *.pdf
```

**Comment by m3nu** [comment]
Some documentation on this was added to the README today. I'm still not fully clear on the actual question. Will close for now. Feel free to reopen with a detailed error report. Thanks.
