### ISSUE TITLE
Better error messages when dependencies for Tesseract are missing

### ISSUE THREAD

**Issue by utsav666** [m3nu/invoice2data#92]
there is an issue with tesseract.py it gives error in line no 7 """"subprocess.Popen(convert.split(' '), stdout=subprocess.PIPE)"""" I repllace the line with this """"subprocess.Popen(convert.split(' '), stdout=subprocess.PIPE,shell=True)"""" but it gives a new error 
""""-density: 1: -density: convert: not found
Error in pixReadMem: size < 12
Error during processing."""""

**Comment by m3nu** [comment]
This error just means that the `imagemagick` library is not installed. This prerequisite should be mentioned in the README. Not sure if it is.

The Tesseract module didn't get much love recently. I'm sure there are some things to improve. Like properly checking for installed prerequisites.

**Comment by m3nu** [comment]
This is almost fixed. Commit still needs some work as the conditions are wrong and there is a typo in the import statement.

**Comment by duskybomb** [comment]
Yes, I don't know how it happened. Make the correction though.
