### ISSUE TITLE
Discussing new approach

### ISSUE THREAD

**Issue by utsav666** [m3nu/invoice2data#95]
Well for initial purpose this repo is absolutely perfect in fetching the entities.......but how could we make this usecase possible using a ml approach(tensorflow,keras etc....).So just to start with the new thought I am sharing a repo which is fetching the table from pdf using ml..here is the link  https://github.com/HazyResearch/TreeStructure .....you can go through this and let have a brainstorming together

**Comment by m3nu** [comment]
Thanks for the input. This direction would be quite interesting. Do you mind if I move this to another issue where I already collected relevant links and ideas? It's #75.

**Comment by m3nu** [comment]
Moved to #75
