### ISSUE TITLE
Unicode Decode error while opening some templates

### ISSUE THREAD

**Issue by sanjay-94** [m3nu/invoice2data#97]
I am getting the following error while opening some templates. 

`templates += read_templates(os.path.abspath(args.template_folder))
  File "/Users/sanjay/code/invoice2data/invoice2data/invoice2data/extract/loader.py", line 47, in read_templates
    tpl = ordered_load(template_file.read())
  File "/Users/sanjay/PycharmProjects/test/venv/bin/../lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]`

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 40: ordinal not in range(128)`

I believe it is something to do with opening the templates in the below lines. 

`with open(os.path.join(path, name)) as template_file:`

When I change the line to 

`with open(os.path.join(path, name), encoding="utf-8") as template_file:`

the error **disappears**. Has the error got something to do with the IDE or the OS? And should we standardise the decoding codec through code, like enforcing it to utf-8?

**Comment by m3nu** [comment]
We already have a similar issue #32.

If you like you can do a pull request for your suggested fix. Instead of passing the `encoding` parameter, you can also consider using the `codec` module, if it's supported in Python 2 and 3. It may be even more reliable than hard-coding a certain encoding.

**Comment by sanjay-94** [comment]
I have made the changes using codec and chardet modules. Sent the PR.

**Comment by sanjay-94** [comment]
Issue has been fixed.
